spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hello-server
        uri: lb://HELLO-SERVER
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<path>.*), /$\{path}
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

